---
server:
  port : 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zerovirus23/spring-cloud-hands-on
          #username: someUser
          #password: somePwd
          search-paths:
          - '/_config-git-files'
          - '/_config-git-files/station*'